//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp_One.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaterAddre
    {
        public int Id { get; set; }
        public string cStreetAddress { get; set; }
        public string cCity { get; set; }
        public string cCountry { get; set; }
        public string cZipCode { get; set; }
        public string cContactNumber { get; set; }
        public string cContactNumber2 { get; set; }
        public int Cater_Id { get; set; }
    
        public virtual Cater Cater { get; set; }
    }
}
